
setopt noautomenu
setopt nomenucomplete

ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3

#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( newline status dir ssh vcs newline dir_writable os_icon)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( newline status dir ssh vcs newline dir_writable )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( command_execution_time background_jobs load ram vi_mode )

POWERLEVEL9K_RAM_BACKGROUND='purple4'
POWERLEVEL9K_RAM_FOREGROUND='grey100'

POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="orangered1"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="orangered1"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="orangered1"
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="grey100"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="grey100"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="grey100"
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="grey100"

POWERLEVEL9K_VCS_CLEAN_BACKGROUND='orangered1'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='grey100'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='orangered1'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='grey100'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='orangered1'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='grey100'

POWERLEVEL9K_DIR_HOME_BACKGROUND='purple4'
POWERLEVEL9K_DIR_HOME_FOREGROUND='grey100'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='purple4'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='grey100'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='purple4'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='grey100'

POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='grey100'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='green'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='grey100'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='orangered1'

POWERLEVEL9K_USER_DEFAULT_BACKGROUND="orange"
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="grey100"

POWERLEVEL9K_OS_ICON_BACKGROUND="green"
POWERLEVEL9K_OS_ICON_FOREGROUND="grey100"

POWERLEVEL9K_STATUS_OK_BACKGROUND="green"
POWERLEVEL9K_STATUS_OK_FOREGROUND="grey100"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="red"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="grey100"

#source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme


#ENABLE_CORRECTION="true"


