#!/bin/sh
for archive in $*; do
    if [ -f $archive ] ; then
        case $archive in
            *.7z)        7z x $archive        ;;
            *.Z)         uncompress $archive  ;;
            *.bz2)       bunzip2 $archive     ;;
            *.gz)        gunzip $archive      ;;
            *.rar)       rar x $archive       ;;
            *.tar)       tar xvf $archive     ;;
            *.tar.bz2)   tar xvjf $archive    ;;
            *.tar.gz)    tar xvzf $archive    ;;
            *.tbz2)      tar xvjf $archive    ;;
            *.tgz)       tar xvzf $archive    ;;
            *.zip)       unzip $archive       ;;
            *)           echo "don't know how to extract '$archive'..." ;;
        esac
    else
        echo "'$archive' is not a valid file!"
    fi
done
